title: "Mi Sitio Jekyll"
description: "Una breve descripción de mi sitio web."
baseurl: "/Portfolio" # Reemplaza con el nombre de tu repositorio
url: "https://Jimy82.github.io"  # Reemplaza con tu usuario de GitHub

